services:
  nginx:
    image: nginx:alpine
    container_name: edaily-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./storage/app/public:/var/www/storage/app/public
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./docker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: edaily-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edaily-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  queue:
    image: edaily-app:latest
    container_name: edaily-queue
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgis/postgis:14-3.4
    container_name: edaily-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot

  renderer:
    image: edaily-renderer:latest
    build:
      context: ./map-renderer-service
      dockerfile: Dockerfile
    container_name: edaily-renderer
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  db_data:
