services:
  # 1. Aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: edaily-app
    container_name: edaily-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db

  # 2. Web Server Nginx
  web:
    image: nginx:alpine
    container_name: edaily-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # 3. Database PostGIS
  db:
    image: postgis/postgis:14-3.4
    container_name: edaily-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # Akses dari luar (opsional, matikan jika ingin private)
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
